### ISSUE TITLE
Can your plugin help solving this nopcommerce search engine problem?

### ISSUE THREAD

**Issue by hassanayoub85** [nixtus/lucene.net-plugin-for-nopcommerce#1]
Hello,
I am facing 2 problems with nopcommerce search engine, and I hope that your plugin can help me out!
I have a product title "Samsung Galaxy Note 10 White" with a description "Samsung Galaxy Note 10 White with Android 10 is one of the best phones in the market..."
I have 2 problems:
1- If I search for "Samsung Note" nopcommerce return nothing, however, if I search for "Samsung Galaxy Note", nopcommerce found it, 
2-If I search for the term "Android 10" it doesn't show the item, so it doesn't search in the description too, I know that I can go to advanced search and select to search in description, but isn't there a way to automatically search in the description?
Thanks

**Comment by mewajda** [comment]
Hi,
I tested both of your scenarios out on my local machine and it looks like it does return what you are looking for in both cases with this plugin.

**Comment by hassanayoub85** [comment]
ok perfect, just tried, but i realised too things:
1- in the auto complete, it didnt show the product which have the android in the description.
2- when i press enter, it show the product, but alose it show alot of products which dont have the word android anywhere in there info like title or description.., so it seems that the returned results are wrong! you can try it on my store technodel.net

**Comment by mewajda** [comment]
I am not sure I follow.  when I enter android and click search, all the products have the word android somewhere in the details when I click into the products.

As for the autocomplete have you downloaded the latest release and enabled autocomplete search?

**Comment by mewajda** [comment]
Closing as this seems to be working correctly. If still facing issues we can reopen
