### ISSUE TITLE
A strongly-named assembly is required. 

### ISSUE THREAD

**Issue by chrisjainsley** [nixtus/lucene.net-plugin-for-nopcommerce#6]
Uploaded the nopCommerce - 4.20 - v0.9.1, hit install and then restart.

Returned the following:

FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
Unknown location

FileLoadException: Could not load file or assembly 'Lucene.Net, Version=4.0.0.0, Culture=neutral, PublicKeyToken=85089178b9ac3181'. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by mewajda** [comment]
@cja100 are you running nopcommerce on Linux or windows?

**Comment by chrisjainsley** [comment]
Turns out I was running a different version of lucene.net in a different plugin, so I changed the plugins version and it worked.
